# NumPy ufuncs

In [1]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [2]:
import numpy as np

def myadd(x, y):
  return x+y

myadd = np.frompyfunc(myadd, 2, 1)

print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [3]:
import numpy as np

print(type(np.add))

<class 'numpy.ufunc'>


In [4]:
import numpy as np

print(type(np.concatenate))

<class 'function'>


In [5]:
import numpy as np

if type(np.add) == np.ufunc:
  print('add is ufunc')
else:
  print('add is not ufunc')

add is ufunc


# Simple Arithmetics

Addition

In [6]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1, arr2)

print(newarr)

[30 32 34 36 38 40]


Subtraction

In [13]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


Multiplication & Division

In [14]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)
arr3 = np.array([10, 20, 30, 40, 50, 60])
arr4 = np.array([3, 5, 10, 8, 2, 33])

newarr1 = np.divide(arr3, arr4)

print("Multiplication: ", newarr)

print("Division: ", newarr1)


Multiplication:  [ 200  420  660  920 1200 1500]
Division:  [ 3.33333333  4.          3.          5.         25.          1.81818182]


Remainde, Quotient & mod

In [3]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr1 = np.remainder(arr1, arr2)

newarr2 = np.divmod(arr1, arr2)

print("Remainder: ", newarr1)

print("Quotient & Mod: ", newarr2)

Remainder:  [ 1  6  3  0  0 27]
Quotient & Mod:  (array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


Absolute Values

In [4]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

[1 2 1 2 3 4]


# Rounding Decimals

In [5]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])
print("Truncation: ", arr)

arr1 = np.around(3.1666, 2)
print("Rounding: ", arr1)

arr2 = np.floor([-3.1666, 3.6667])
print("Floor Value: ", arr2)

arr3 = np.ceil([-3.1666, 3.6667])
print("Ceil Value: ", arr3)

Truncation:  [-3.  3.]
Rounding:  3.17
Floor Value:  [-4.  3.]
Ceil Value:  [-3.  4.]


# Numpy Logs

Log at base 2

In [6]:
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


Log at Base 10

In [7]:
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


Natural Log, or Log at Base e

In [8]:
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


Log at Any Base

In [9]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


# NumPy Summations

Summations(Add the values in arr1 to the values in arr2)

In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.add(arr1, arr2)

print(newarr)

[2 4 6]


Summations(Sum the values in arr1 and the values in arr2)

In [12]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2])

print(newarr)

12


Summation Over an Axis

In [13]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

newarr = np.sum([arr1, arr2], axis=1)

print(newarr)

[6 6]


Cummulative Sum

In [14]:
import numpy as np

arr = np.array([1, 2, 3])

newarr = np.cumsum(arr)

print(newarr)

[1 3 6]


# NumPy LCM

Finding LCM 

In [15]:
import numpy as np

num1 = 4
num2 = 6

x = np.lcm(num1, num2)

print(x)

12


Finding LCM in Arrays

In [16]:
import numpy as np

arr = np.array([3, 6, 9])

x = np.lcm.reduce(arr)

print(x)

18


LCM of all values of an array where the array contains all integers from 1 to 10

In [17]:
import numpy as np

arr = np.arange(1, 11)

x = np.lcm.reduce(arr)

print(x)

2520


# NumPy GCD

Finding GCD

In [18]:
import numpy as np

num1 = 6
num2 = 9

x = np.gcd(num1, num2)

print(x)

3


Finding GCD in Arrays

In [19]:
import numpy as np

arr = np.array([20, 8, 32, 36, 16])

x = np.gcd.reduce(arr)

print(x)

4
